# Generated by Django 4.0.2 on 2022-02-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0002_alter_article_options_alter_article_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='changed',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменено'),
        ),
    ]
